const translations = {
  en: {
    // Auth Page
    auth_welcome_title: "Welcome to Pizza Hut",
    auth_welcome_subtitle: "Login to access your orders, favorites, and more.",
    loginTitle: "🍕 Welcome Back!",
    loginSubtext: "Log in to get your favorites delivered hot & fast.",
    loginCta: "→ Log In & Order Now",
    signupTitle: "🎉 Join the Pizza Party!",
    signupSubtext: "Sign up & get 20% OFF your first order.",
    signupCta: "→ Create Account",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    confirmPasswordPlaceholder: "Confirm Password",
    forgotPassword: "Forgot password?",
    noAccountPrompt: "Don't have an account?",
    signupLink: "Sign Up",
    hasAccountPrompt: "Already have an account?",
    loginLink: "Login",
    orSeparator: "OR",
    googleBtn: "Sign in with Google",
    terms: 'I agree to the <a href="terms.html" class="text-blue-600 hover:underline">Terms and Conditions</a>.',
    resetTitle: "Reset Password",
    resetSubtext: "Enter your email and we'll send a reset link.",
    sendResetLink: "Send Reset Link",
    cancel: "Cancel",
    strength: { weak: "Weak", medium: "Medium", strong: "Strong" },
    loadingLogin: "Logging in...",
    loadingSignup: "Creating Account...",
    errorInvalidEmail: "Please enter a valid email address.",
    errorUserNotFound: "No account found with this email. Please sign up.",
    errorWrongPassword: "Incorrect password. Please try again.",
    errorWeakPassword: "Password should be at least 6 characters.",
    errorEmailInUse: "This email address is already in use.",
    errorPhoneInUse: "This phone number is already in use.",
    errorGeneric: "An unexpected error occurred. Please try again.",
    errorFieldRequired: "This field is required.",
    auth_login_btn: "Login / Sign Up",

    // Order Type Selection
    order_type_selection_title: "How will you get your order?",
    order_type_selection_subtitle: "Choose an option to start your order.",
    order_type_to_go: "Self Pick Up",
    order_type_to_go_desc: "Collect your order from the store.",
    order_type_delivery: "Delivery",
    order_type_delivery_desc: "Get your order delivered to your door.",

    // Menu Page
    auth_welcome_back: "Welcome back,",
    my_account: "My Account",
    tab_settings: "Account Settings",
    my_orders: "My Orders",
    my_favorites: "My Favorites",
    offers: "Offers",
    help: "Help",
    support: "Support",
    faq: "FAQ",
    terms: "Terms & Conditions",
    logout_button: "Log Out",
    loading_menu: "Loading menu...",
    no_results_found: "No results found",
    try_searching_else: "Try searching for something else.",
    view_cart: "View Cart",
    customize: "Customize",
    add_to_cart: "Add",

    // Other shared keys
    message_box_ok: "OK",
  },
  fr: {
    // Auth Page
    auth_welcome_title: "Bienvenue chez Pizza Hut",
    auth_welcome_subtitle: "Connectez-vous pour accéder à vos commandes, favoris, et plus.",
    loginTitle: "🍕 Content de te revoir !",
    loginSubtext: "Connecte-toi pour commander ta pizza préférée.",
    loginCta: "→ Se connecter et commander",
    signupTitle: "🎉 Rejoins la famille Pizza !",
    signupSubtext: "Inscris-toi et reçois 20% de réduction.",
    signupCta: "→ Créer un compte",
    emailPlaceholder: "Adresse e-mail",
    passwordPlaceholder: "Mot de passe",
    confirmPasswordPlaceholder: "Confirmer le mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    noAccountPrompt: "Pas encore de compte ?",
    signupLink: "S'inscrire",
    hasAccountPrompt: "Déjà un compte ?",
    loginLink: "Se connecter",
    orSeparator: "OU",
    googleBtn: "Se connecter avec Google",
    terms: 'J\'accepte les <a href="terms.html" class="text-blue-600 hover:underline">Termes et Conditions</a>.',
    resetTitle: "Réinitialiser le mot de passe",
    resetSubtext: "Entrez votre email et nous enverrons un lien.",
    sendResetLink: "Envoyer le lien",
    cancel: "Annuler",
    strength: { weak: "Faible", medium: "Moyen", strong: "Fort" },
    loadingLogin: "Connexion...",
    loadingSignup: "Création du compte...",
    errorInvalidEmail: "Veuillez saisir une adresse e-mail valide.",
    errorUserNotFound: "Aucun compte trouvé avec cet e-mail. Veuillez vous inscrire.",
    errorWrongPassword: "Mot de passe incorrect. Veuillez réessayer.",
    errorWeakPassword: "Le mot de passe doit comporter au moins 6 caractères.",
    errorEmailInUse: "Cette adresse e-mail est déjà utilisée.",
    errorPhoneInUse: "Ce numéro de téléphone est déjà utilisé.",
    errorGeneric: "Une erreur inattendue est survenue. Veuillez réessayer.",
    errorFieldRequired: "Ce champ est requis.",
    auth_login_btn: "Connexion / Inscription",

    // Order Type Selection
    order_type_selection_title: "Comment voulez-vous votre commande ?",
    order_type_selection_subtitle: "Choisissez une option pour commencer.",
    order_type_to_go: "À emporter",
    order_type_to_go_desc: "Récupérez votre commande au restaurant.",
    order_type_delivery: "Livraison",
    order_type_delivery_desc: "Faites-vous livrer votre commande.",

    // Menu Page
    auth_welcome_back: "Bon retour,",
    my_account: "Mon Compte",
    tab_settings: "Paramètres du compte",
    my_orders: "Mes Commandes",
    my_favorites: "Mes Favoris",
    offers: "Offres",
    help: "Aide",
    support: "Support",
    faq: "FAQ",
    terms: "Termes & Conditions",
    logout_button: "Déconnexion",
    loading_menu: "Chargement du menu...",
    no_results_found: "Aucun résultat trouvé",
    try_searching_else: "Essayez une autre recherche.",
    view_cart: "Voir le panier",
    customize: "Personnaliser",
    add_to_cart: "Ajouter",

    // Other shared keys
    message_box_ok: "OK",
  },
  ar: {
    // Auth Page
    auth_welcome_title: "أهلاً بك في بيتزا هت",
    auth_welcome_subtitle: "سجل الدخول للوصول إلى طلباتك والمفضلة والمزيد.",
    loginTitle: "🍕 مرحباً بعودتك!",
    loginSubtext: "سجّل الدخول واطلب بيتزاك المفضلة الآن.",
    loginCta: "→ تسجيل الدخول والطلب الآن",
    signupTitle: "🎉 انضم لعشاق البيتزا!",
    signupSubtext: "سجّل الآن واحصل على خصم 20٪.",
    signupCta: "→ إنشاء حساب",
    emailPlaceholder: "البريد الإلكتروني",
    passwordPlaceholder: "كلمة المرور",
    confirmPasswordPlaceholder: "تأكيد كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    noAccountPrompt: "ليس لديك حساب؟",
    signupLink: "إنشاء حساب",
    hasAccountPrompt: "لديك حساب بالفعل؟",
    loginLink: "تسجيل الدخول",
    orSeparator: "أو",
    googleBtn: "تسجيل الدخول عبر جوجل",
    terms: 'أوافق على <a href="terms.html" class="text-blue-600 hover:underline">الشروط والأحكام</a>.',
    resetTitle: "إعادة تعيين كلمة المرور",
    resetSubtext: "أدخل بريدك الإلكتروني وسنرسل لك رابطًا.",
    sendResetLink: "إرسال الرابط",
    cancel: "إلغاء",
    strength: { weak: "ضعيف", medium: "متوسط", strong: "قوي" },
    loadingLogin: "جاري تسجيل الدخول...",
    loadingSignup: "جاري إنشاء الحساب...",
    errorInvalidEmail: "يرجى إدخال بريد إلكتروني صالح.",
    errorUserNotFound: "لم يتم العثور على حساب بهذا البريد الإلكتروني. الرجاء التسجيل.",
    errorWrongPassword: "كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.",
    errorWeakPassword: "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.",
    errorEmailInUse: "هذا البريد الإلكتروني مستخدم بالفعل.",
    errorPhoneInUse: "رقم الهاتف هذا مستخدم بالفعل.",
    errorGeneric: "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    errorFieldRequired: "هذا الحقل مطلوب.",
    auth_login_btn: "تسجيل الدخول / إنشاء حساب",
    
    // Order Type Selection
    order_type_selection_title: "كيف ستستلم طلبك؟",
    order_type_selection_subtitle: "اختر إحدى الخيارات للبدء.",
    order_type_to_go: "استلام من المطعم",
    order_type_to_go_desc: "استلم طلبك من المطعم.",
    order_type_delivery: "توصيل",
    order_type_delivery_desc: "احصل على طلبك حتى باب منزلك.",

    // Menu Page
    auth_welcome_back: "أهلاً بعودتك،",
    my_account: "حسابي",
    tab_settings: "إعدادات الحساب",
    my_orders: "طلباتي",
    my_favorites: "المفضلة",
    offers: "العروض",
    help: "مساعدة",
    support: "الدعم",
    faq: "الأسئلة الشائعة",
    terms: "الشروط والأحكام",
    logout_button: "تسجيل الخروج",
    loading_menu: "جاري تحميل القائمة...",
    no_results_found: "لم يتم العثور على نتائج",
    try_searching_else: "حاول البحث عن شيء آخر.",
    view_cart: "عرض السلة",
    customize: "تخصيص",
    add_to_cart: "إضافة",

    // Other shared keys
    message_box_ok: "موافق",
  }
};