const translations = {
  en: {
    validation_error_title: "Validation Error",
    table_number_missing_error: "Please enter a valid table number.",
    cart_empty_order_error: "Your cart is empty. Please add items before placing an order.",
    placing_order_feedback: "Placing Order...",
    order_error_title: "Order Error",
    order_placement_error_message: "There was a problem placing your order online. Please try again.",
    message_box_ok: "OK",
    cart_total_label: "Total:",
    order_summary_title: "Order Summary",
    loading_order_details: "Loading order details...",
    error_fetching_order: "Error fetching order details.",
    order_placed_at: "Placed at:",
    items_heading: "Items",
    status_label: "Status:",
    done_button: "Done",
    save_pdf_button: "Save as PDF",
    generating_pdf_feedback: "Generating PDF...",

    my_orders: "My Orders",

    auth_customer_login: "Customer Login",
    auth_create_account: "Create Account",
    auth_email_placeholder: "Email",
    auth_password_placeholder: "Password",
    auth_login_btn: "Login",
    auth_signup_link: "Sign Up",
    auth_have_account: "Don't have an account?",
    auth_already_have_account: "Already have an account?",
    auth_confirm_password_placeholder: "Confirm Password",
    auth_phone_placeholder: "Phone Number (Optional)",
    auth_name_placeholder: "Full Name (Optional)",
    auth_signup_btn: "Sign Up",
    auth_login_error_invalid_credentials: "Invalid email or password.",
    auth_login_error_user_not_found: "No user found with this email.",
    auth_login_error_wrong_password: "Incorrect password.",
    auth_login_error_invalid_email_format: "Invalid email format.",
    auth_signup_error_email_in_use: "This email is already in use.",
    auth_signup_error_weak_password: "Password is too weak (should be at least 6 characters).",
    auth_signup_error_invalid_email_format: "Invalid email format.",
    auth_signup_error_generic: "Error signing up. Please try again.",
    auth_password_mismatch: "Passwords do not match.",

    order_type_title: "How would you like your order?",
    order_type_to_go: "Take Away (To-Go)",
    order_type_delivery: "Delivery",
    order_type_dine_in: "Dine-in",
    order_type_toGo: "Take Away (To-Go)",
    order_type_dineIn: "Dine-in",

    logged_in_as: "Logged in as",
    logout_button: "Logout",
    no_user_logged_in: "No user is logged in. Please log in first.",

    customer_name_label: "Customer Name",
    phone_number_label: "Phone Number",
    delivery_address_label: "Delivery Address",
    incorrect_info_prompt: "Is your information incorrect?",
    edit_profile_link: "Edit Profile",
    order_type_missing_error: "Order type is not set. Please select how you want to order.",

    profile_title: "My Profile",
    update_profile_button: "Update Profile",
    updating_profile_feedback: "Updating Profile...",
    profile_success_title: "Profile Updated",
    profile_update_success: "Your profile has been successfully updated!",
    profile_error_title: "Profile Error",
    profile_load_error: "Error loading your profile details.",
    profile_update_error: "Error updating your profile. Please try again.",
    name_missing_error: "Full Name is required for to-go and delivery orders.",

    order_confirmed: "✅ Thank you for your order!",
    order_received: "Your order has been received and is being prepared.",
    noOrderData: "No order data found for this ID.",
    back_to_menu: "Back to Menu",

    status_pending: "Pending",
    status_preparing: "Preparing",
    status_out_for_delivery: "Out for Delivery",
    status_delivered: "Delivered"
  },

  fr: {
    validation_error_title: "Erreur de Validation",
    table_number_missing_error: "Veuillez entrer un numéro de table valide.",
    cart_empty_order_error: "Votre panier est vide. Veuillez ajouter des articles avant de passer commande.",
    placing_order_feedback: "Commande en cours...",
    order_error_title: "Erreur de Commande",
    order_placement_error_message: "Un problème est survenu lors de votre commande en ligne. Veuillez réessayer.",
    message_box_ok: "OK",
    cart_total_label: "Total :",
    order_summary_title: "Résumé de la Commande",
    loading_order_details: "Chargement des détails de la commande...",
    error_fetching_order: "Erreur lors de la récupération des détails de la commande.",
    order_placed_at: "Passée le :",
    items_heading: "Articles",
    status_label: "Statut :",
    done_button: "Terminé",
    save_pdf_button: "Enregistrer en PDF",
    generating_pdf_feedback: "Génération du PDF...",

    my_orders: "Mes Commandes",

    auth_customer_login: "Connexion Client",
    auth_create_account: "Créer un Compte",
    auth_email_placeholder: "Email",
    auth_password_placeholder: "Mot de passe",
    auth_login_btn: "Connexion",
    auth_signup_link: "S'inscrire",
    auth_have_account: "Vous n'avez pas de compte ?",
    auth_already_have_account: "Vous avez déjà un compte ?",
    auth_confirm_password_placeholder: "Confirmer le mot de passe",
    auth_phone_placeholder: "Numéro de téléphone (Facultatif)",
    auth_name_placeholder: "Nom complet (Facultatif)",
    auth_signup_btn: "S'inscrire",
    auth_login_error_invalid_credentials: "Email ou mot de passe invalide.",
    auth_login_error_user_not_found: "Aucun utilisateur trouvé avec cet email.",
    auth_login_error_wrong_password: "Mot de passe incorrect.",
    auth_login_error_invalid_email_format: "Format d'email invalide.",
    auth_signup_error_email_in_use: "Cet email est déjà utilisé.",
    auth_signup_error_weak_password: "Mot de passe trop faible (doit contenir au moins 6 caractères).",
    auth_signup_error_invalid_email_format: "Format d'email invalide.",
    auth_signup_error_generic: "Erreur lors de l'inscription. Veuillez réessayer.",
    auth_password_mismatch: "Les mots de passe ne correspondent pas.",

    order_type_title: "Comment souhaitez-vous votre commande ?",
    order_type_to_go: "À emporter",
    order_type_delivery: "Livraison",
    order_type_dine_in: "Sur place",
    order_type_toGo: "À emporter",
    order_type_dineIn: "Sur place",

    logged_in_as: "Connecté en tant que",
    logout_button: "Déconnexion",
    no_user_logged_in: "Aucun utilisateur n'est connecté. Veuillez vous connecter d'abord.",

    customer_name_label: "Nom du client",
    phone_number_label: "Numéro de téléphone",
    delivery_address_label: "Adresse de livraison",
    incorrect_info_prompt: "Vos informations sont-elles incorrectes ?",
    edit_profile_link: "Modifier le profil",
    order_type_missing_error: "Le type de commande n'est pas défini. Veuillez sélectionner comment vous souhaitez commander.",

    profile_title: "Mon Profil",
    update_profile_button: "Mettre à jour le profil",
    updating_profile_feedback: "Mise à jour du profil...",
    profile_success_title: "Profil mis à jour",
    profile_update_success: "Votre profil a été mis à jour avec succès !",
    profile_error_title: "Erreur de profil",
    profile_load_error: "Erreur lors du chargement de vos informations de profil.",
    profile_update_error: "Erreur lors de la mise à jour de votre profil. Veuillez réessayer.",
    name_missing_error: "Le nom complet est requis pour les commandes à emporter et les livraisons.",

    order_confirmed: "✅ Merci pour votre commande !",
    order_received: "Votre commande a été reçue et est en cours de préparation.",
    noOrderData: "Aucune donnée de commande trouvée pour cet ID.",
    back_to_menu: "Retour au Menu",

    status_pending: "En attente",
    status_preparing: "En préparation",
    status_out_for_delivery: "En livraison",
    status_delivered: "Livré"
  },

  ar: {
    validation_error_title: "خطأ في التحقق",
    table_number_missing_error: "الرجاء إدخال رقم طاولة صحيح.",
    cart_empty_order_error: "سلة التسوق فارغة. الرجاء إضافة عناصر قبل تقديم الطلب.",
    placing_order_feedback: "جاري تقديم الطلب...",
    order_error_title: "خطأ في الطلب",
    order_placement_error_message: "حدثت مشكلة أثناء تقديم طلبك عبر الإنترنت. الرجاء المحاولة مرة أخرى.",
    message_box_ok: "موافق",
    cart_total_label: "المجموع:",
    order_summary_title: "ملخص الطلب",
    loading_order_details: "جاري تحميل تفاصيل الطلب...",
    error_fetching_order: "حدث خطأ أثناء جلب تفاصيل الطلب.",
    order_placed_at: "وقت الطلب:",
    items_heading: "العناصر",
    status_label: "الحالة:",
    done_button: "تم",
    save_pdf_button: "حفظ كـ PDF",
    generating_pdf_feedback: "جاري إنشاء PDF...",

    my_orders: "طلباتي",

    auth_customer_login: "تسجيل دخول العميل",
    auth_create_account: "إنشاء حساب",
    auth_email_placeholder: "البريد الإلكتروني",
    auth_password_placeholder: "كلمة المرور",
    auth_login_btn: "تسجيل الدخول",
    auth_signup_link: "إنشاء حساب",
    auth_have_account: "ليس لديك حساب؟",
    auth_already_have_account: "لديك حساب بالفعل؟",
    auth_confirm_password_placeholder: "تأكيد كلمة المرور",
    auth_phone_placeholder: "رقم الهاتف (اختياري)",
    auth_name_placeholder: "الاسم الكامل (اختياري)",
    auth_signup_btn: "إنشاء حساب",
    auth_login_error_invalid_credentials: "بريد إلكتروني أو كلمة مرور غير صحيحة.",
    auth_login_error_user_not_found: "لم يتم العثور على مستخدم بهذا البريد الإلكتروني.",
    auth_login_error_wrong_password: "كلمة المرور غير صحيحة.",
    auth_login_error_invalid_email_format: "تنسيق البريد الإلكتروني غير صالح.",
    auth_signup_error_email_in_use: "هذا البريد الإلكتروني مستخدم بالفعل.",
    auth_signup_error_weak_password: "كلمة المرور ضعيفة جدًا (يجب أن تتكون من 6 أحرف على الأقل).",
    auth_signup_error_invalid_email_format: "تنسيق البريد الإلكتروني غير صالح.",
    auth_signup_error_generic: "حدث خطأ أثناء التسجيل. الرجاء المحاولة مرة أخرى.",
    auth_password_mismatch: "كلمات المرور غير متطابقة.",

    order_type_title: "كيف تريد طلبك؟",
    order_type_to_go: "جاهز (للتوصيل)",
    order_type_delivery: "توصيل",
    order_type_dine_in: "لتناول الطعام هنا",
    order_type_toGo: "جاهز (للتوصيل)",
    order_type_dineIn: "لتناول الطعام هنا",

    logged_in_as: "تم تسجيل الدخول باسم",
    logout_button: "تسجيل الخروج",
    no_user_logged_in: "لم يتم تسجيل دخول أي مستخدم. الرجاء تسجيل الدخول أولاً.",

    customer_name_label: "اسم العميل",
    phone_number_label: "رقم الهاتف",
    delivery_address_label: "عنوان التسليم",
    incorrect_info_prompt: "هل معلوماتك غير صحيحة؟",
    edit_profile_link: "تعديل الملف الشخصي",
    order_type_missing_error: "نوع الطلب غير محدد. يرجى اختيار كيفية الطلب.",

    profile_title: "ملفي الشخصي",
    update_profile_button: "تحديث الملف الشخصي",
    updating_profile_feedback: "جاري تحديث الملف الشخصي...",
    profile_success_title: "تم تحديث الملف الشخصي",
    profile_update_success: "تم تحديث ملفك الشخصي بنجاح!",
    profile_error_title: "خطأ في الملف الشخصي",
    profile_load_error: "حدث خطأ أثناء تحميل تفاصيل ملفك الشخصي.",
    profile_update_error: "حدث خطأ أثناء تحديث ملفك الشخصي. الرجاء المحاولة مرة أخرى.",
    name_missing_error: "الاسم الكامل مطلوب لطلبات التوصيل والخارج.",

    order_confirmed: "✅ شكراً لطلبك!",
    order_received: "تم استلام طلبك ويتم تحضيره الآن.",
    noOrderData: "لم يتم العثور على بيانات الطلب لهذا المعرف.",
    back_to_menu: "العودة إلى القائمة",

    status_pending: "معلق",
    status_preparing: "قيد التحضير",
    status_out_for_delivery: "في الطريق للتوصيل",
    status_delivered: "تم التوصيل"
  }
};
